#!/usr/bin/env python3
"""
Week 2 - Task 5: Comprehensive Test Suite
Tests 10 different scenarios for token system
"""

import time
from colorama import Fore, init
from week2_task1_master_key import MasterKeyDerivation
from week2_task2_token_generation import TokenGenerator
from week2_task3_proof_validation import ProofValidator

init(autoreset=True)

def run_all_tests():
    """Run all 10 test scenarios"""
    print(f"{Fore.CYAN}{'='*60}")
    print(f"{Fore.CYAN}WEEK 2 - TASK 5: 10 Test Scenarios")
    print(f"{Fore.CYAN}{'='*60}\n")
    
    mkd = MasterKeyDerivation()
    pv = ProofValidator()
    
    password = "TestPassword123!"
    master_key, salt = mkd.derive_master_key(password)
    tg = TokenGenerator(master_key)
    
    passed = 0
    failed = 0
    
    # Test 1: Valid token for correct file
    print(f"{Fore.YELLOW}Test 1: Valid token for correct file")
    nonce_c = tg.generate_nonce()
    nonce_s = tg.generate_nonce()
    timestamp = int(time.time())
    filepath = "/docs/file.txt"
    token = tg.generate_token(nonce_c, nonce_s, timestamp, filepath)
    
    # Validate
    token_check = tg.generate_token(nonce_c, nonce_s, timestamp, filepath)
    if token == token_check:
        print(f"{Fore.GREEN}✅ PASS\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL\n")
        failed += 1
    
    # Test 2: Valid token for wrong file (should fail)
    print(f"{Fore.YELLOW}Test 2: Valid token for wrong file")
    wrong_file = "/docs/other.txt"
    token_wrong = tg.generate_token(nonce_c, nonce_s, timestamp, wrong_file)
    if token != token_wrong:
        print(f"{Fore.GREEN}✅ PASS - Token rejected for wrong file\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Same token for different files\n")
        failed += 1
    
    # Test 3: Expired token (after 10 minutes)
    print(f"{Fore.YELLOW}Test 3: Expired token")
    old_timestamp = timestamp - 700  # 11+ minutes ago
    old_token = tg.generate_token(nonce_c, nonce_s, old_timestamp, filepath)
    if old_token != token:
        print(f"{Fore.GREEN}✅ PASS - Old token is different\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Token doesn't change with time\n")
        failed += 1
    
    # Test 4: Wrong password
    print(f"{Fore.YELLOW}Test 4: Wrong password")
    wrong_master_key, _ = mkd.derive_master_key("WrongPassword")
    tg_wrong = TokenGenerator(wrong_master_key)
    wrong_token = tg_wrong.generate_token(nonce_c, nonce_s, timestamp, filepath)
    if token != wrong_token:
        print(f"{Fore.GREEN}✅ PASS - Wrong password produces different token\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Same token with wrong password\n")
        failed += 1
    
    # Test 5: Replayed token (used twice)
    print(f"{Fore.YELLOW}Test 5: Replay attack prevention")
    challenge1 = pv.generate_challenge()
    challenge2 = pv.generate_challenge()
    proof1 = pv.create_proof(token, challenge1)
    # Try to reuse proof1 with challenge2
    if not pv.validate_proof(token, challenge2, proof1):
        print(f"{Fore.GREEN}✅ PASS - Replay attack prevented\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Replay attack succeeded\n")
        failed += 1
    
    # Test 6: Token generated by different device (same master key)
    print(f"{Fore.YELLOW}Test 6: Cross-device token generation")
    # Simulate device 1
    device1_tg = TokenGenerator(master_key)
    device1_token = device1_tg.generate_token(nonce_c, nonce_s, timestamp, filepath)
    
    # Simulate device 2
    device2_tg = TokenGenerator(master_key)
    device2_token = device2_tg.generate_token(nonce_c, nonce_s, timestamp, filepath)
    
    if device1_token == device2_token:
        print(f"{Fore.GREEN}✅ PASS - Both devices generate same token\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Devices generate different tokens\n")
        failed += 1
    
    # Test 7: Modified token (tampered)
    print(f"{Fore.YELLOW}Test 7: Tampered token detection")
    tampered_token = token[:-1] + "x"  # Change last character
    if token != tampered_token:
        print(f"{Fore.GREEN}✅ PASS - Tampered token detected\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Tampered token not detected\n")
        failed += 1
    
    # Test 8: Token with special characters in filename
    print(f"{Fore.YELLOW}Test 8: Special characters in filename")
    special_file = "/docs/file with spaces & symbols!@#.txt"
    special_token = tg.generate_token(nonce_c, nonce_s, timestamp, special_file)
    special_check = tg.generate_token(nonce_c, nonce_s, timestamp, special_file)
    if special_token == special_check:
        print(f"{Fore.GREEN}✅ PASS - Special characters handled correctly\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Special characters cause issues\n")
        failed += 1
    
    # Test 9: Token with wrong timestamp
    print(f"{Fore.YELLOW}Test 9: Wrong timestamp")
    wrong_timestamp = timestamp + 1
    wrong_time_token = tg.generate_token(nonce_c, nonce_s, wrong_timestamp, filepath)
    if token != wrong_time_token:
        print(f"{Fore.GREEN}✅ PASS - Wrong timestamp produces different token\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Timestamp doesn't affect token\n")
        failed += 1
    
    # Test 10: Concurrent tokens for different files
    print(f"{Fore.YELLOW}Test 10: Concurrent tokens for different files")
    file1 = "/docs/file1.txt"
    file2 = "/docs/file2.txt"
    token1 = tg.generate_token(nonce_c, nonce_s, timestamp, file1)
    token2 = tg.generate_token(nonce_c, nonce_s, timestamp, file2)
    if token1 != token2:
        print(f"{Fore.GREEN}✅ PASS - Different tokens for different files\n")
        passed += 1
    else:
        print(f"{Fore.RED}❌ FAIL - Same token for different files\n")
        failed += 1
    
    # Summary
    print(f"{Fore.CYAN}{'='*60}")
    print(f"{Fore.CYAN}TEST SUMMARY")
    print(f"{Fore.CYAN}{'='*60}")
    print(f"{Fore.GREEN}Passed: {passed}/10")
    print(f"{Fore.RED}Failed: {failed}/10")
    
    if failed == 0:
        print(f"\n{Fore.GREEN}🎉 ALL TESTS PASSED!")
        print(f"{Fore.GREEN}Week 2 Task 5 Complete!")
    else:
        print(f"\n{Fore.RED}⚠️  Some tests failed. Review implementation.")
    
    print(f"{Fore.CYAN}{'='*60}\n")

if __name__ == "__main__":
    run_all_tests()