// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ClearAllEvents():Promise<void>;

export function DisableAntispy():Promise<void>;

export function DisableKillswitch():Promise<void>;

export function EnableAntispy():Promise<void>;

export function EnableKillswitch():Promise<void>;

export function GetEventDetails(arg1:app.Event):Promise<app.EventDetails>;

export function GetEvents():Promise<Array<app.Event>>;

export function GetSettings():Promise<app.Settings>;

export function IsAntispyActive():Promise<boolean>;

export function IsKillswitchActive():Promise<boolean>;

export function LookupVirusTotal(arg1:string):Promise<app.VirusTotalReport>;

export function Quit():Promise<void>;

export function RescanVirusTotal(arg1:string):Promise<app.VirusTotalReport>;

export function ResumeProcess(arg1:number):Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function Show():Promise<void>;

export function ShowMainWindow():Promise<void>;

export function SuspendProcess(arg1:number):Promise<void>;

export function TerminateProcess(arg1:number):Promise<void>;

export function UpdateSettings(arg1:app.Settings):Promise<app.Settings>;

export function UploadVirusTotal(arg1:string):Promise<app.VirusTotalReport>;
