// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllEvents() {
  return window['go']['app']['App']['ClearAllEvents']();
}

export function DisableAntispy() {
  return window['go']['app']['App']['DisableAntispy']();
}

export function DisableKillswitch() {
  return window['go']['app']['App']['DisableKillswitch']();
}

export function EnableAntispy() {
  return window['go']['app']['App']['EnableAntispy']();
}

export function EnableKillswitch() {
  return window['go']['app']['App']['EnableKillswitch']();
}

export function GetEventDetails(arg1) {
  return window['go']['app']['App']['GetEventDetails'](arg1);
}

export function GetEvents() {
  return window['go']['app']['App']['GetEvents']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function IsAntispyActive() {
  return window['go']['app']['App']['IsAntispyActive']();
}

export function IsKillswitchActive() {
  return window['go']['app']['App']['IsKillswitchActive']();
}

export function LookupVirusTotal(arg1) {
  return window['go']['app']['App']['LookupVirusTotal'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RescanVirusTotal(arg1) {
  return window['go']['app']['App']['RescanVirusTotal'](arg1);
}

export function ResumeProcess(arg1) {
  return window['go']['app']['App']['ResumeProcess'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['app']['App']['RevealPath'](arg1);
}

export function Show() {
  return window['go']['app']['App']['Show']();
}

export function ShowMainWindow() {
  return window['go']['app']['App']['ShowMainWindow']();
}

export function SuspendProcess(arg1) {
  return window['go']['app']['App']['SuspendProcess'](arg1);
}

export function TerminateProcess(arg1) {
  return window['go']['app']['App']['TerminateProcess'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UploadVirusTotal(arg1) {
  return window['go']['app']['App']['UploadVirusTotal'](arg1);
}
